DOC_METADATA_EXAMPLE = {
    "seqNumber": 1,
    "docID": "S100WGLE",
    "edinetCode": "E40761",
    "secCode": None,
    "JCN": "7010401190011",
    "filerName": "ＯＰＩ・１８株式会社",
    "fundCode": None,
    "ordinanceCode": "040",
    "formCode": "060007",
    "docTypeCode": "270",
    "periodStart": None,
    "periodEnd": None,
    "submitDateTime": "2025-08-05 09:00",
    "docDescription": "公開買付報告書",
    "issuerEdinetCode": None,
    "subjectEdinetCode": "E33109",
    "subsidiaryEdinetCode": None,
    "currentReportReason": None,
    "parentDocID": "S100VYQI",
    "opeDateTime": None,
    "withdrawalStatus": "0",
    "docInfoEditStatus": "0",
    "disclosureStatus": "0",
    "xbrlFlag": "1",
    "pdfFlag": "1",
    "attachDocFlag": "0",
    "englishDocFlag": "0",
    "csvFlag": "1",
    "legalStatus": "1",
}
